services:
  shinebuild:
    image: ghcr.io/sisbios/shinebuild-app:${IMAGE_TAG:-latest}
    container_name: shinebuild
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
